import { useEffect, useState, type ReactNode } from 'react';
import {
  Activity, AlertTriangle, BarChart3, Bell, CheckCircle2, ClipboardCheck, Clock3,
  HeartPulse, Home, Languages, LockKeyhole, Menu, Mic, Moon, ShieldCheck, UserRound,
  Users, X, LogOut, Settings, ChevronRight, Brain, CalendarDays, Dumbbell, Database,
} from 'lucide-react';
import { Link, Route, Switch, useLocation, Router } from 'wouter';
import { MotionTracking } from '@/components/motion-tracking';

type Lang = 'en' | 'ta' | 'hi';
type Role = 'personnel' | 'welfare' | 'commander' | 'admin';
type Risk = 'LOWER' | 'MODERATE' | 'ELEVATED';

type Wellness = {
  stress: number; sleep: number; fatigue: number; workload: number; connection: number;
  updatedAt: string;
};

type Personnel = {
  id: string; name: string; rank: string; unit: string; deploymentDays: number;
  dutyHours: number; leaveGap: number; trainingLoad: number; restHours: number;
  transferCount: number; wellness: Wellness;
};

const seedPersonnel: Personnel[] = [
  { id:'PF-1024', name:'A. Kumar', rank:'Inspector', unit:'Unit Alpha', deploymentDays:42, dutyHours:58, leaveGap:18, trainingLoad:82, restHours:7, transferCount:2, wellness:{stress:4,sleep:2,fatigue:4,workload:5,connection:3,updatedAt:'Today'} },
  { id:'PF-1087', name:'R. Singh', rank:'Sub-Inspector', unit:'Unit Alpha', deploymentDays:27, dutyHours:49, leaveGap:26, trainingLoad:61, restHours:7, transferCount:1, wellness:{stress:3,sleep:3,fatigue:3,workload:4,connection:4,updatedAt:'Today'} },
  { id:'PF-1142', name:'S. Das', rank:'Constable', unit:'Unit Bravo', deploymentDays:19, dutyHours:44, leaveGap:12, trainingLoad:48, restHours:8, transferCount:0, wellness:{stress:2,sleep:4,fatigue:2,workload:3,connection:4,updatedAt:'Yesterday'} },
  { id:'PF-1198', name:'M. Devi', rank:'Head Constable', unit:'Unit Bravo', deploymentDays:35, dutyHours:54, leaveGap:31, trainingLoad:74, restHours:6, transferCount:2, wellness:{stress:4,sleep:2,fatigue:4,workload:4,connection:2,updatedAt:'Today'} },
  { id:'PF-1210', name:'N. Ali', rank:'Constable', unit:'Unit Charlie', deploymentDays:11, dutyHours:41, leaveGap:9, trainingLoad:38, restHours:8, transferCount:0, wellness:{stress:2,sleep:4,fatigue:2,workload:2,connection:4,updatedAt:'Today'} },
];

function riskScore(p: Personnel) {
  const w=p.wellness;
  return Math.round(
    Math.min(100,
      p.dutyHours*0.45 + p.deploymentDays*0.22 + p.leaveGap*0.18 +
      p.trainingLoad*0.08 + Math.max(0,8-p.restHours)*6 +
      (w.stress+w.fatigue+w.workload+(6-w.sleep))*5
    )
  );
}
function riskOf(p: Personnel): Risk {
  const s=riskScore(p);
  return s>=65?'ELEVATED':s>=42?'MODERATE':'LOWER';
}
function riskLabel(r: Risk) { return r==='LOWER'?'Lower indicators':r==='MODERATE'?'Moderate attention':'Elevated support indicators'; }

const copy = {
  en:{title:'NeuroFlex',subtitle:'AI-Powered Personnel Stress & Welfare Support',home:'Dashboard',check:'Wellness Check-In',trends:'Wellness Trends',workload:'Duty & Workload',welfare:'Welfare Dashboard',alerts:'Alerts',privacy:'Privacy & Consent',motion:'Motion Tracking',settings:'Settings',welcome:'Personnel Wellness Dashboard',startCheck:'Complete wellness check-in',myStatus:'My wellness status',risk:'Welfare indicator',recommend:'Recommendations',save:'Save check-in',stress:'Stress',sleep:'Sleep quality',fatigue:'Fatigue',workloadScore:'Workload',connection:'Support connection',hours:'Duty hours/week',deployment:'Deployment days',leave:'Days since leave',rest:'Rest hours/night',training:'Training load',consent:'Consent & privacy',consentText:'Wellness data is voluntary. This prototype is for welfare support, not diagnosis or disciplinary decisions.',language:'Language',role:'Role',personnel:'Personnel',welfareOfficer:'Welfare Officer',commander:'Commander',admin:'Administrator',privacyTitle:'Privacy by design',privacyBody:'Use consent, role-based access, anonymized analytics and audit trails before any real deployment.',explain:'Why this indicator?',recommendations:'Welfare recommendations',view:'View details',noAlerts:'No new welfare alerts.',demo:'Synthetic demo data',signOut:'Sign out'},
  ta:{title:'NeuroFlex',subtitle:'AI அடிப்படையிலான பணியாளர் நலன் ஆதரவு',home:'டாஷ்போர்டு',check:'நலன் மதிப்பீடு',trends:'நலன் போக்குகள்',workload:'பணி மற்றும் சுமை',welfare:'நல அலுவலர் டாஷ்போர்டு',alerts:'எச்சரிக்கைகள்',privacy:'தனியுரிமை மற்றும் ஒப்புதல்',motion:'இயக்க கண்காணிப்பு',settings:'அமைப்புகள்',welcome:'பணியாளர் நலன் டாஷ்போர்டு',startCheck:'நலன் மதிப்பீட்டை தொடங்குங்கள்',myStatus:'என் நல நிலை',risk:'நல குறியீடு',recommend:'பரிந்துரைகள்',save:'மதிப்பீட்டை சேமி',stress:'மன அழுத்தம்',sleep:'தூக்க தரம்',fatigue:'சோர்வு',workloadScore:'பணி சுமை',connection:'ஆதரவு தொடர்பு',hours:'வார பணி நேரம்',deployment:'பணியமர்த்தல் நாட்கள்',leave:'கடைசி விடுப்பிலிருந்து நாட்கள்',rest:'இரவு ஓய்வு நேரம்',training:'பயிற்சி சுமை',consent:'ஒப்புதல் மற்றும் தனியுரிமை',consentText:'நலன் தரவு தன்னார்வமானது. இது மருத்துவ நோயறிதல் அல்லது ஒழுங்கு நடவடிக்கைக்கான கருவி அல்ல.',language:'மொழி',role:'பங்கு',personnel:'பணியாளர்',welfareOfficer:'நல அலுவலர்',commander:'தளபதி',admin:'நிர்வாகி',privacyTitle:'தனியுரிமை முதன்மை',privacyBody:'உண்மையான பயன்பாட்டிற்கு முன் ஒப்புதல், பங்கு அடிப்படையிலான அணுகல், அடையாளமற்ற பகுப்பாய்வு மற்றும் audit பதிவுகள் பயன்படுத்தப்பட வேண்டும்.',explain:'இந்த குறியீடு ஏன்?',recommendations:'நலன் பரிந்துரைகள்',view:'விவரங்களை பார்க்க',noAlerts:'புதிய நல எச்சரிக்கைகள் இல்லை.',demo:'செயற்கை டெமோ தரவு',signOut:'வெளியேறு'},
  hi:{title:'NeuroFlex',subtitle:'AI आधारित कार्मिक तनाव और कल्याण सहायता',home:'डैशबोर्ड',check:'कल्याण जांच',trends:'कल्याण रुझान',workload:'ड्यूटी और कार्यभार',welfare:'कल्याण डैशबोर्ड',alerts:'अलर्ट',privacy:'गोपनीयता और सहमति',motion:'मोशन ट्रैकिंग',settings:'सेटिंग्स',welcome:'कार्मिक कल्याण डैशबोर्ड',startCheck:'कल्याण जांच पूरी करें',myStatus:'मेरी कल्याण स्थिति',risk:'कल्याण संकेतक',recommend:'सिफारिशें',save:'जांच सेव करें',stress:'तनाव',sleep:'नींद की गुणवत्ता',fatigue:'थकान',workloadScore:'कार्यभार',connection:'सहायता संपर्क',hours:'साप्ताहिक ड्यूटी घंटे',deployment:'तैनाती के दिन',leave:'अवकाश से दिन',rest:'रात्रि विश्राम घंटे',training:'प्रशिक्षण भार',consent:'सहमति और गोपनीयता',consentText:'कल्याण डेटा स्वैच्छिक है। यह चिकित्सा निदान या अनुशासनात्मक निर्णय के लिए नहीं है।',language:'भाषा',role:'भूमिका',personnel:'कार्मिक',welfareOfficer:'कल्याण अधिकारी',commander:'कमांडर',admin:'प्रशासक',privacyTitle:'गोपनीयता पहले',privacyBody:'वास्तविक उपयोग से पहले सहमति, भूमिका-आधारित पहुंच, अनाम विश्लेषण और ऑडिट ट्रेल आवश्यक हैं।',explain:'यह संकेतक क्यों?',recommendations:'कल्याण सिफारिशें',view:'विवरण देखें',noAlerts:'कोई नया कल्याण अलर्ट नहीं।',demo:'सिंथेटिक डेमो डेटा',signOut:'साइन आउट'}
};

function Card({children,className='' }:{children:ReactNode;className?:string}){return <section className={'rounded-2xl border bg-card p-5 shadow-sm '+className}>{children}</section>}
function Badge({risk}:{risk:Risk}){return <span className={'rounded-full px-3 py-1 text-xs font-semibold '+(risk==='ELEVATED'?'bg-red-100 text-red-700':risk==='MODERATE'?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700')}>{riskLabel(risk)}</span>}
function Metric({label,value,icon:Icon}:{label:string;value:string|number;icon:any}){return <div className="rounded-xl border p-4"><Icon className="mb-2 h-5 w-5"/><div className="text-2xl font-bold">{value}</div><div className="text-sm text-muted-foreground">{label}</div></div>}

function AppShell({lang,setLang,role,setRole,children}:{lang:Lang;setLang:(l:Lang)=>void;role:Role;setRole:(r:Role)=>void;children:ReactNode}){
  const c=copy[lang]; const [open,setOpen]=useState(false); const [location]=useLocation();
  const links=[['/','home',Home],['/check-in','check',ClipboardCheck],['/trends','trends',BarChart3],['/workload','workload',CalendarDays], ...(role!=='personnel'?[['/welfare','welfare',Users]]:[]),['/alerts','alerts',Bell],['/motion','motion',Activity],['/privacy','privacy',LockKeyhole]];
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3">
      <div className="flex items-center gap-3"><button className="md:hidden" onClick={()=>setOpen(!open)}><Menu/></button><div className="rounded-xl bg-primary p-2 text-primary-foreground"><HeartPulse/></div><div><div className="font-bold">{c.title}</div><div className="text-xs text-muted-foreground">{c.subtitle}</div></div></div>
      <div className="flex items-center gap-2"><select aria-label={c.language} value={lang} onChange={e=>setLang(e.target.value as Lang)} className="rounded-lg border bg-background px-2 py-1 text-sm"><option value="en">English</option><option value="ta">தமிழ்</option><option value="hi">हिन्दी</option></select><select aria-label={c.role} value={role} onChange={e=>setRole(e.target.value as Role)} className="hidden rounded-lg border bg-background px-2 py-1 text-sm md:block"><option value="personnel">{c.personnel}</option><option value="welfare">{c.welfareOfficer}</option><option value="commander">{c.commander}</option><option value="admin">{c.admin}</option></select></div>
    </div></header>
    <div className="mx-auto flex max-w-7xl"><aside className={(open?'block':'hidden')+' fixed inset-x-0 top-[65px] z-30 bg-background p-3 md:static md:block md:w-64 md:border-r md:bg-transparent md:p-4'}><nav className="space-y-1">{links.map(([href,key,Icon])=><Link key={href} href={href as string}><a onClick={()=>setOpen(false)} className={'flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm '+(location===href?'bg-primary text-primary-foreground':'hover:bg-muted')}><Icon className="h-4 w-4"/>{c[key as keyof typeof c]}</a></Link>)}</nav></aside><main className="min-w-0 flex-1 p-4 md:p-6">{children}</main></div>
  </div>
}

function HomePage({c,personnel}:{c:any;personnel:Personnel[]}){
  const me=personnel[0], risk=riskOf(me), elevated=personnel.filter(p=>riskOf(p)==='ELEVATED').length;
  return <div className="space-y-6"><div><p className="text-sm text-muted-foreground">{c.demo}</p><h1 className="text-3xl font-bold">{c.welcome}</h1><p className="mt-1 text-muted-foreground">AI-assisted early welfare indicators, workload context and explainable support recommendations. Prototype uses transparent feature scoring; it is not a medical diagnosis.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label={c.risk} value={riskLabel(risk)} icon={ShieldCheck}/><Metric label="Personnel monitored" value={personnel.length} icon={Users}/><Metric label="Elevated indicators" value={elevated} icon={AlertTriangle}/><Metric label="Average duty hours" value={Math.round(personnel.reduce((a,p)=>a+p.dutyHours,0)/personnel.length)+'h'} icon={Clock3}/></div>
    <div className="grid gap-5 lg:grid-cols-3"><Card className="lg:col-span-2"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">{c.myStatus}</h2><p className="text-sm text-muted-foreground">Synthetic personnel profile: {me.id}</p></div><Badge risk={risk}/></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label={c.stress} value={me.wellness.stress+'/5'} icon={Brain}/><Metric label={c.sleep} value={me.wellness.sleep+'/5'} icon={Moon}/><Metric label={c.fatigue} value={me.wellness.fatigue+'/5'} icon={Activity}/><Metric label={c.workloadScore} value={me.wellness.workload+'/5'} icon={BarChart3}/></div></Card>
    <Card><h2 className="font-semibold">{c.recommendations}</h2><ul className="mt-3 space-y-3 text-sm">{recommendations(me).map(x=><li key={x} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0"/>{x}</li>)}</ul></Card></div>
    <Card><div className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-5 w-5"/>{c.consent}</div><p className="mt-2 text-sm text-muted-foreground">{c.consentText}</p></Card>
  </div>
}
function recommendations(p:Personnel){const r=riskOf(p); const a:string[]=[]; if(p.dutyHours>52)a.push('Review workload and duty rotation.'); if(p.restHours<7)a.push('Consider a rest/recovery review.'); if(p.leaveGap>28)a.push('Review leave availability and welfare needs.'); if(p.wellness.fatigue>=4)a.push('Offer a confidential welfare check-in.'); if(!a.length)a.push('Continue current wellness routine and periodic check-ins.'); if(r==='ELEVATED')a.push('Authorized welfare personnel should review the pattern confidentially.'); return a}
function CheckIn({lang,setPersonnel}:{lang:Lang;setPersonnel:React.Dispatch<React.SetStateAction<Personnel[]>>}){const c=copy[lang]; const [vals,setVals]=useState({stress:3,sleep:3,fatigue:3,workload:3,connection:3}); const save=()=>setPersonnel(ps=>ps.map((p,i)=>i? p:{...p,wellness:{...vals,updatedAt:'Just now'}})); const fields=[['stress',c.stress],['sleep',c.sleep],['fatigue',c.fatigue],['workload',c.workloadScore],['connection',c.connection]] as const; return <Card><h1 className="text-2xl font-bold">{c.check}</h1><p className="mt-1 text-sm text-muted-foreground">Voluntary wellness screening. It does not diagnose a medical condition.</p><div className="mt-6 space-y-5">{fields.map(([k,label])=><label key={k} className="block"><div className="mb-2 flex justify-between"><span>{label}</span><b>{vals[k]}/5</b></div><input className="w-full" type="range" min="1" max="5" value={vals[k]} onChange={e=>setVals(v=>({...v,[k]:Number(e.target.value)}))}/></label>)}</div><button onClick={save} className="mt-6 rounded-xl bg-primary px-5 py-2.5 text-primary-foreground">{c.save}</button></Card>}
function Trends({personnel}:{personnel:Personnel[]}){const p=personnel[0]; return <div className="space-y-5"><h1 className="text-2xl font-bold">Wellness Trends</h1><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Stress" value={p.wellness.stress+'/5'} icon={Brain}/><Metric label="Fatigue" value={p.wellness.fatigue+'/5'} icon={Activity}/><Metric label="Sleep" value={p.wellness.sleep+'/5'} icon={Moon}/><Metric label="Workload" value={p.wellness.workload+'/5'} icon={BarChart3}/></div><Card><h2 className="font-semibold">Recent pattern</h2><div className="mt-5 space-y-4">{[['Stress',p.wellness.stress],['Sleep quality',p.wellness.sleep],['Fatigue',p.wellness.fatigue],['Workload',p.wellness.workload]].map(([l,v])=><div key={l as string}><div className="mb-1 flex justify-between text-sm"><span>{l}</span><span>{v}/5</span></div><div className="h-3 rounded-full bg-muted"><div className="h-3 rounded-full bg-primary" style={{width:(Number(v)/5*100)+'%'}}/></div></div>)}</div></Card></div>}
function Workload({personnel}:{personnel:Personnel[]}){return <div className="space-y-5"><h1 className="text-2xl font-bold">Duty & Workload Analytics</h1><div className="grid gap-4 md:grid-cols-3"><Metric label="Average duty hours" value={Math.round(personnel.reduce((a,p)=>a+p.dutyHours,0)/personnel.length)+'h'} icon={Clock3}/><Metric label="Average deployment" value={Math.round(personnel.reduce((a,p)=>a+p.deploymentDays,0)/personnel.length)+' days'} icon={CalendarDays}/><Metric label="Average rest" value={(personnel.reduce((a,p)=>a+p.restHours,0)/personnel.length).toFixed(1)+'h'} icon={Moon}/></div><Card><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Personnel</th><th className="p-3">Duty</th><th className="p-3">Deployment</th><th className="p-3">Leave gap</th><th className="p-3">Training</th><th className="p-3">Rest</th><th className="p-3">Indicator</th></tr></thead><tbody>{personnel.map(p=><tr key={p.id} className="border-b last:border-0"><td className="p-3 font-medium">{p.id}</td><td className="p-3">{p.dutyHours}h</td><td className="p-3">{p.deploymentDays}d</td><td className="p-3">{p.leaveGap}d</td><td className="p-3">{p.trainingLoad}%</td><td className="p-3">{p.restHours}h</td><td className="p-3"><Badge risk={riskOf(p)}/></td></tr>)}</tbody></table></div></Card></div>}
function Welfare({personnel}:{personnel:Personnel[]}){const elevated=personnel.filter(p=>riskOf(p)==='ELEVATED'), moderate=personnel.filter(p=>riskOf(p)==='MODERATE'); return <div className="space-y-5"><div><h1 className="text-2xl font-bold">Welfare Officer Dashboard</h1><p className="text-sm text-muted-foreground">Use indicators to prioritize confidential human review; do not automate disciplinary decisions.</p></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Lower" value={personnel.length-elevated.length-moderate.length} icon={CheckCircle2}/><Metric label="Moderate" value={moderate.length} icon={AlertTriangle}/><Metric label="Elevated" value={elevated.length} icon={ShieldCheck}/></div><Card><div className="space-y-3">{personnel.map(p=><div key={p.id} className="flex flex-col gap-3 rounded-xl border p-4 md:flex-row md:items-center md:justify-between"><div><div className="font-semibold">{p.id} · {p.rank}</div><div className="text-sm text-muted-foreground">{p.unit} · workload {p.wellness.workload}/5 · fatigue {p.wellness.fatigue}/5</div></div><div className="flex items-center gap-3"><Badge risk={riskOf(p)}/><span className="text-sm">{riskScore(p)} indicator score</span></div></div>)}</div></Card></div>}
function Alerts({personnel}:{personnel:Personnel[]}){const alerts=personnel.filter(p=>riskOf(p)!=='LOWER'); return <div className="space-y-5"><h1 className="text-2xl font-bold">Welfare Alerts</h1>{alerts.length?<div className="space-y-3">{alerts.map(p=><Card key={p.id}><div className="flex gap-3"><AlertTriangle className="h-5 w-5 shrink-0"/><div className="flex-1"><div className="flex flex-wrap items-center gap-2 font-semibold">{p.id}<Badge risk={riskOf(p)}/></div><p className="mt-2 text-sm text-muted-foreground">Pattern includes {p.dutyHours} duty hours/week, {p.restHours} hours rest/night and fatigue {p.wellness.fatigue}/5.</p><p className="mt-2 text-sm">Suggested action: confidential welfare review and workload/rest assessment.</p></div></div></Card>)}</div>:<Card>{copy.en.noAlerts}</Card>}</div>}
function Privacy({c}:{c:any}){const [consent,setConsent]=useState(()=>localStorage.getItem('nf-consent')==='yes'); return <div className="space-y-5"><h1 className="text-2xl font-bold">{c.privacyTitle}</h1><Card><div className="grid gap-4 md:grid-cols-2"><Metric label="Consent" value="Required" icon={CheckCircle2}/><Metric label="Access" value="Role-based" icon={LockKeyhole}/><Metric label="Analytics" value="Anonymized" icon={Database}/><Metric label="Audit" value="Enabled in prototype" icon={ShieldCheck}/></div><p className="mt-5 text-sm text-muted-foreground">{c.privacyBody}</p><label className="mt-5 flex items-start gap-3 rounded-xl border p-4"><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);localStorage.setItem('nf-consent',e.target.checked?'yes':'no')}} className="mt-1"/><span className="text-sm"><b>Voluntary wellness consent</b><br/>Allow this prototype to store your wellness check-in on this device. Optional motion/biometric-style measurements remain separate and require an explicit start action.</span></label></Card><Card><h2 className="font-semibold">Data handling principles</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm"><li>Collect only necessary welfare information.</li><li>Separate voluntary wellness data from organizational records.</li><li>Show individual details only to authorized roles.</li><li>Use synthetic/demo data during development and evaluation.</li><li>Keep human welfare review in the decision loop.</li></ul></Card></div>}
function Protected({allowed,role,children}:{allowed:Role[];role:Role;children:ReactNode}){return allowed.includes(role)?<>{children}</>:<Card><h1 className="text-xl font-bold">Authorized role required</h1><p className="mt-2 text-sm text-muted-foreground">This welfare information is restricted to authorized roles.</p></Card>}\nfunction App(){const [lang,setLang]=useState<Lang>(()=>(localStorage.getItem('nf-lang') as Lang)||'en'); const [role,setRole]=useState<Role>(()=>(localStorage.getItem('nf-role') as Role)||'personnel'); const [personnel,setPersonnel]=useState<Personnel[]>(()=>{try{return JSON.parse(localStorage.getItem('nf-personnel')||'null')||seedPersonnel}catch{return seedPersonnel}}); useEffect(()=>localStorage.setItem('nf-lang',lang),[lang]); useEffect(()=>localStorage.setItem('nf-role',role),[role]); useEffect(()=>localStorage.setItem('nf-personnel',JSON.stringify(personnel)),[personnel]); const c=copy[lang]; return <AppShell lang={lang} setLang={setLang} role={role} setRole={setRole}><Switch><Route path="/check-in"><CheckIn lang={lang} setPersonnel={setPersonnel}/></Route><Route path="/trends"><Trends personnel={personnel}/></Route><Route path="/workload"><Workload personnel={personnel}/></Route><Route path="/welfare"><Protected allowed={["welfare","commander","admin"]} role={role}><Welfare personnel={personnel}/></Protected></Route><Route path="/alerts"><Protected allowed={["welfare","commander","admin"]} role={role}><Alerts personnel={personnel}/></Protected></Route><Route path="/motion"><MotionTracking/></Route><Route path="/privacy"><Privacy c={c}/></Route><Route><HomePage c={c} personnel={personnel}/></Route></Switch></AppShell>}
export default function Root(){return <Router><App/></Router>}
